--ADD NEW EFFECTS

--Leadin fx new list
ABC_Template			= table.duplicate(PfxM_Box);  table.inbox(ABC_Template, "lead-in[fx]: ABC Template","Syl",true,false,"#F6F3F3","#ADC4D6","#6A8DD6","0","0","0","l.start_time","l.end_time","","","","","syl.center","syl.middle","","","5","0","fx.pos_x","fx.pos_y","","1","","syl.text","",""); table.insert(leadin_fx_library, 1, ABC_Template); table.insert(leadin_fx, 1, "ABC Template")
Cristal_Text_buttLine	= table.duplicate(PfxM_Box);  table.inbox(Cristal_Text_buttLine, "lead-in[fx]: Cristal Text buttLine","Syl",true,false,"#FFFFFF","#008DFF","#000000","0","0","0","l.start_time + time_mid2(40) - 35*syl.n - var.syl.delay - 20*R(25)","l.start_time + time_mid2(40) - 35*syl.n","0","0","0","0","syl.center","syl.middle","0","0","5","0","fx.pos_x + var.loop.dx, fx.pos_x","fx.pos_y + var.loop.dy, fx.pos_y","","17","","syl.text","format('%s\\\\fr%s\\\\t(\\\\fr0)\\\\fad(300,0)', shape.movevc(shape.cristal17, 'tag', 1.2*syl.width, syl.height), R(-360,360))","delay = 500, dx = R(25, 50)*ratio*(-1)^r(2), dy = R(25, 50)*ratio*(-1)^r(2)"); table.insert(leadin_fx_library, Cristal_Text_buttLine); table.insert(leadin_fx, "Cristal Text buttLine")
Cristal_Text_midLine	= table.duplicate(PfxM_Box);  table.inbox(Cristal_Text_midLine, "lead-in[fx]: Cristal Text midLine","Syl",true,false,"#FFFFFF","#008DFF","#000000","0","0","0","l.start_time + time_mid1(40) - 35*syl.n - var.syl.delay - 20*R(25)","l.start_time + time_mid1(40) - 35*syl.n","0","0","0","0","syl.center","syl.middle","0","0","5","0","fx.pos_x + var.loop.dx, fx.pos_x","fx.pos_y + var.loop.dy, fx.pos_y","","17","","syl.text","format('%s\\\\fr%s\\\\t(\\\\fr0)\\\\fad(300,0)', shape.movevc(shape.cristal17, 'tag', 1.2*syl.width, syl.height), R(-360,360))","delay = 500, dx = R(25, 50)*ratio*(-1)^r(2), dy = R(25, 50)*ratio*(-1)^r(2)"); table.insert(leadin_fx_library, Cristal_Text_midLine); table.insert(leadin_fx, "Cristal Text midLine")
Cristal_Text_preline	= table.duplicate(PfxM_Box);  table.inbox(Cristal_Text_preline, "lead-in[fx]: Cristal Text preline","Syl",true,false,"#FFFFFF","#008DFF","#000000","0","0","0","l.start_time - var.syl.delay - 20*R(25)","l.start_time","0","0","0","0","syl.center","syl.middle","0","0","5","0","fx.pos_x + var.loop.dx, fx.pos_x","fx.pos_y + var.loop.dy, fx.pos_y","","17","","syl.text","format('%s\\\\fr%s\\\\t(\\\\fr0)\\\\fad(300,0)', shape.movevc(shape.cristal17, 'tag', 1.2*syl.width, syl.height), R(-360,360))","delay = 500, dx = R(25, 50)*ratio*(-1)^r(2), dy = R(25, 50)*ratio*(-1)^r(2)"); table.insert(leadin_fx_library, Cristal_Text_preline); table.insert(leadin_fx, "Cristal Text preline")
Cristal_Text_start2syl	= table.duplicate(PfxM_Box);  table.inbox(Cristal_Text_start2syl, "lead-in[fx]: Cristal Text start2syl","Syl",true,false,"#FFFFFF","#008DFF","#000000","0","0","0","l.start_time + 50*(syl.i - syl.n/2 - 1) - var.syl.delay - 20*R(25)","l.start_time + 50*(syl.i - syl.n/2 - 1)","0","0","0","0","syl.center","syl.middle","0","0","5","0","fx.pos_x + var.loop.dx, fx.pos_x","fx.pos_y + var.loop.dy, fx.pos_y","","17","","syl.text","format('%s\\\\fr%s\\\\t(\\\\fr0)\\\\fad(300,0)', shape.movevc(shape.cristal17, 'tag', 1.2*syl.width, syl.height), R(-360,360))","delay = 500, dx = R(25, 50)*ratio*(-1)^r(2), dy = R(25, 50)*ratio*(-1)^r(2)"); table.insert(leadin_fx_library, Cristal_Text_start2syl); table.insert(leadin_fx, "Cristal Text start2syl")


--Hilight fx new list
Spectrum_Horizontal		= table.duplicate(PfxM_Box);  table.inbox(Spectrum_Horizontal, "hi-light[fx]: Spectrum Horizontal","Syl",true,false,"#F6F3F3","#ADC4D6","#6A8DD6","0","0","0","l.start_time + syl.start_time","l.start_time + syl.end_time + 200","","","","","syl.center","syl.middle","","","5","1","fx.pos_x","fx.pos_y","","12","","syl.text","format('\\\\org(%s, -10000)%s\\\\fad(0,200)%s', fx.pos_x, tag.clip(0, fx.pos_t, xres, syl.height), tag.oscill(fx.dur, 120, '\\\\fr'..var.syl.Angle*(-1)^j, '\\\\fr'..var.syl.Angle*(-1)^(j+1)))","Angle = 0.03"); table.insert(hilight_fx_library, Spectrum_Horizontal); table.insert(hilight_fx, "Spectrum Horizontal")
Spectrum_Vertical		= table.duplicate(PfxM_Box);  table.inbox(Spectrum_Vertical, "hi-light[fx]: Spectrum Vertical","Syl",true,false,"#F6F3F3","#ADC4D6","#6A8DD6","0","0","0","l.start_time + syl.start_time","l.start_time + syl.end_time + 200","","","","","syl.center","syl.middle","","","5","1","fx.pos_x","fx.pos_y","","1, 12","","syl.text","format('\\\\org(%s, %s)%s\\\\fad(0,200)%s', fx.pos_x - 10000, fx.pos_y, tag.clip(fx.pos_l, 0, syl.width, yres), tag.oscill(fx.dur, 120, '\\\\fr'..var.syl.Angle*(-1)^j, '\\\\fr'..var.syl.Angle*(-1)^(j+1)))","Angle = 0.03"); table.insert(hilight_fx_library, Spectrum_Vertical); table.insert(hilight_fx, "Spectrum Vertical")


--Leadout fx new list
Senoidal_Move_I			= table.duplicate(PfxM_Box);  table.inbox(Senoidal_Move_I, "lead-out[fx]: Senoidal Move I","Syl",true,false,"#F6F3F3","#ADC4D6","#6A8DD6","0","0","0","l.start_time + syl.end_time","l.start_time + syl.end_time + 400 + 20*j","","","","","syl.center","syl.middle","","","5","0","fx.pos_x, fx.pos_x","fx.pos_y, fx.pos_y - var.syl.Dx","","16","","syl.text","format('\\\\org(%s, -10000)%s\\\\fad(0,200)%s\\\\t(%s)', fx.pos_x, tag.clip(fx.pos_l - 100, fx.pos_t, syl.width + 200, syl.height, 17), tag.oscill(fx.dur, 60, var.loop.Ang(3.5, 0.025)), tag.clip(fx.pos_l - 100, fx.pos_t - var.syl.Dx, syl.width + 200, syl.height, 17))","Ang = function(Domain, angle) ang = angle or 0.04 a = {} for i = 0, 3 do a[i + 1] = math.round(ang*sin(Domain*pi*module + i*pi/2), 3) end return table.concat1(a, '\\\\fr') end, Dx = 26*ratio"); table.insert(leadout_fx_library, Senoidal_Move_I); table.insert(leadout_fx, "Senoidal Move I")


--Shape fx new list
Sakura_Blur_I			= table.duplicate(Shape_Box); table.inbox(Sakura_Blur_I, "shape[fx]: Sakura Blur I","Syl",true,false,"#FFFFFF","#5D406D","#6A8DD6","255","40","0","l.start_time + syl.start_time - 200","l.start_time + syl.end_time + 300","","","","","syl.center","syl.middle","","","5","0","fx.pos_x","fx.pos_y","","1","10","shape.flower5t","format('\\\\fr%s\\\\t(\\\\fr0)\\\\t(0,200,\\\\fscx75\\\\fscy75)\\\\fad(200,300)\\\\bord4\\\\blur6', 0.08*fx.dur)",""); table.insert(shape_fx_library, Sakura_Blur_I); table.insert(shape_fx, "Sakura Blur I")
Sakura_Blur_II			= table.duplicate(Shape_Box); table.inbox(Sakura_Blur_II, "shape[fx]: Sakura Blur II","Syl",true,false,"#FFFFFF","#2EB9C8","#6A8DD6","45","40","0","l.start_time + syl.start_time - 200","l.start_time + syl.end_time + 300","","","","","syl.center + 2","syl.middle","","","5","1","fx.pos_x","fx.pos_y - 20","","5","10","var.syl.petal","format('\\\\org(%s,%s)\\\\fr%s\\\\t(\\\\fr%s)\\\\t(0,200,\\\\fscx50\\\\fscy50)\\\\fad(200,0)\\\\bord2\\\\blur4', x, y, 0.08*fx.dur + 72*(j - 1), 72*(j - 1))","petal = 'm 25 53 b 37 36 50 18 25 0 b 0 18 13 36 25 53 b 6 7 45 7 25 53 '"); table.insert(shape_fx_library, Sakura_Blur_II); table.insert(shape_fx, "Sakura Blur II")
Sakura_Blur_III			= table.duplicate(Shape_Box); table.inbox(Sakura_Blur_III, "shape[fx]: Sakura Blur III","Syl",true,false,"#FFFFFF","#2EB9C8","#6A8DD6","45","40","0","l.start_time + syl.end_time + 300","fx.start_time + 1200 + r(100, 400)","","","","","syl.center + 2","syl.middle","","","5","1","fx.pos_x, fx.pos_x - r(80, 180)","fx.pos_y, fx.pos_y + r(-10, 60)","50*(j - 1), fx.dur","5","50","var.syl.petal","format('\\\\fsvp20\\\\fr%s\\\\fad(0,500)\\\\t(\\\\fscx25\\\\fscy25\\\\frx%s\\\\fry%s\\\\fr%s)\\\\bord2\\\\blur4', 72*(j - 1), r(-360,360), r(-360,360), r(-360,360))","petal = 'm 25 53 b 37 36 50 18 25 0 b 0 18 13 36 25 53 b 6 7 45 7 25 53 '"); table.insert(shape_fx_library, Sakura_Blur_III); table.insert(shape_fx, "Sakura Blur III")


--Translation fx new list
ABC_Translation_Line	= table.duplicate(Trans_Box); table.inbox(ABC_Translation_Line, "translation[fx]: ABC Translation Line","Translation Line",true,false,"#FFFFFF","#008DFF","#000000","0","0","0","l.start_time","l.end_time","","","","","line.center","line.middle","","","5","0","fx.pos_x","fx.pos_y","","1","","line.text_stripped","",""); table.insert(transla_fx_library, 1, ABC_Translation_Line); table.insert(transla_fx, 1, "ABC Translation Line")
Move_Line_Top			= table.duplicate(Trans_Box); table.inbox(Move_Line_Top, "translation[fx]: Move Line Top","Translation Line",true,false,"#FFFFFF","#008DFF","#000000","0","0","0","l.start_time - var.line.delay","l.end_time","","","","","line.center","line.middle","","","5","0","fx.pos_x","fx.pos_y - var.line.d, fx.pos_y","0, var.line.delay","1","","line.text_stripped","format('\\\\shad0\\\\bord2\\\\1c&HFFFFFF&\\\\3c&HFFFFFF&\\\\blur3\\\\t(%s,%s,\\\\shad%s\\\\bord%s\\\\1c%s\\\\3c%s)\\\\fad(0,300)', 3*var.line.delay/4, var.line.delay, l.shadow, l.outline, text.color1, text.color3)","d = l.height, delay = 260"); table.insert(transla_fx_library, Move_Line_Top); table.insert(transla_fx, "Move Line Top")